# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            'seq2seq-attn'
tagline:          'NMT'
description:      'A general purpose <a href="http://jekyllrb.com" target="_blank">attentional sequence-to-sequence</a> system. Made by Yoon Kim and <a href="https://twitter.com/harvardnlp" target="_blank">@harvardnlp</a>.'
url:              http://harvardnlp.github.io/
baseurl:          /

author:
  name:           'Yoon Kim and HarvardNLP'
  url:            https://twitter.com/harvardnlp


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/harvardnlp/seq2seq-attn
